apiVersion: v1
items:
- apiVersion: v1
  data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImEzQnJhWE5vYjNKbE9rQTFSR1puYUdwcmJBPT0iCgkJfQoJfQp9
  kind: Secret
  metadata:
    creationTimestamp: "2022-08-15T09:16:51Z"
    name: regcred
    namespace: webapp
    resourceVersion: "147025"
    uid: 8b741705-8788-463e-afb4-10f764456492
  type: kubernetes.io/dockerconfig.json
kind: List
metadata:
  resourceVersion: ""
